# Dependencies
highlighter:      rouge

# lsi:              true

# Permalinks
permalink:        pretty

# Setup
title:            Matouš Michalík
tagline:          'co dělám a co umím'
description:      ''
url:              https://matousmichalik.com

GA:               UA-34538626-1

disqus:           matousuvzapisnik

excerpt_separator: '\n\n'

encoding:         utf-8

author:
  name:           'Matouš Michalík'
  email:          blog@matousmichalik.com
  fb:             https://www.facebook.com/iMatrosh
  linkedin:       https://cz.linkedin.com/in/matousmichalik
  fbid:           1454569676

paginate:         5
paginate_path:    "/blog/:num/"

plugins: [jekyll-paginate]

include: ['.well-known']
exclude:
  - deploy.sh
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock

# Custom vars

separator:        '<!-- more -->'
